

=== Configure OpenAPI documentation for a multi-module application

// This example only applies to 2.0 forward, and so the file and directory must be manually copied and applied to any new versions. Copy the directory and file and change the directory name to reflect the new feature version, for example `mpOpenAPI-3.2`.

By default, all deployed applications and modules are included in the OpenAPI documentation. However, you can configure which applications and modules should be included.

For example, the following configuration is for the `sample_app` application, which consists of an `EAR` file containing five web modules.

[source,xml]
----
<mpOpenAPI>
  <excludeModule>sample_app/module-3</excludeModule>
  <excludeModule>sample_app/module-5</excludeModule>
  <info title="A multi-module sample application"
        description="This is a sample application."
        version="2.0.1"
        termsOfService="http://example.com/sample_app/terms"
        contactName="API Support"
        contactUrl="http://www.example.com/sample_app/support"
        contactEmail="sample_app_support@example.com"
        licenseName="License 2.0"
        licenseUrl="https://www.example.org/licenses/LICENSE-2.0.html"
        />
</mpOpenAPI>
----

- The `<excludeModule>` elements exclude the `module-3` and `module-5` web modules.

- The `<info>` element sets the info section for the final OpenAPI document, which documents web modules 1, 2, and 4.

For more information, see xref:ROOT:documentation-openapi.adoc#multi-module[Multiple application and multi-module application support with MicroProfile OpenAPI]