== Examples

=== Enable Open Telemetry

=== Prepare your development environment for Open Telemetry

[#logs]
=== Log settings
The following examples show common optional settings to configure the collection and export of OpenTelemetry log data.

==== Collect logs from a specified source

To enable the MicroProfile Telemetry feature to collect logs from different sources in the Open Liberty runtime environment, configure the `source` attribute for the `mpTelemetry` element with a comma-separated list of comma-separated log sources.

[source,xml]
----
<mpTelemetry source="message, trace, ffdc"/>
----

* The `mpTelemetry` configuration element is optional. If you do not specify ity or the `source` attribute, the default configuration source is `message`.

* If the source attribute is empty (`source=“”`), no sources are collected, and nothing is routed to the configured OpenTelemetry logs exporter.

* The attributes and values are case insensitive.

[#metrics]
=== Metrics settings
The following examples show common optional settings to configure the collection and export of OpenTelemetry metrics data.

[#trace]
=== Trace settings
The following examples show common optional settings to configure the collection and export of OpenTelemetry trace data.


===
